language: php

sudo: false

php:
  - 7.1
  - 7.2
  - 8.0

env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-ansi --no-progress --no-suggest"

before_install:
  - composer self-update
  - composer clear-cache

install:
  - composer install

script:
  - mkdir -p build/logs
  - composer test
  - composer test-coverage

after_success:
  - travis_retry php vendor/bin/php-coveralls -v
  - echo "Success!"

notifications:
  email: false

